const StatesById = {
  'andaman-and-nicobar-islands': 'Andaman and Nicobar Islands',
  'andhra-pradesh': 'Andhra Pradesh',
  'arunachal-pradesh': 'Arunachal Pradesh',
  assam: 'Assam',
  bihar: 'Bihar',
  chandigarh: 'Chandigarh',
  chhattisgarh: 'Chhattisgarh',
  'daman-and-diu': 'Daman and Diu',
  delhi: 'Delhi',
  'dadra-and-nagar-haveli': 'Dadra and Nagar Haveli',
  goa: 'Goa',
  gujarat: 'Gujarat',
  'himachal-pradesh': 'Himachal Pradesh',
  haryana: 'Haryana',
  jharkhand: 'Jharkhand',
  'jammu-and-kashmir': 'Jammu and Kashmir',
  karnataka: 'Karnataka',
  kerala: 'Kerala',
  lakshadweep: 'Lakshadweep',
  maharashtra: 'Maharashtra',
  meghalaya: 'Meghalaya',
  manipur: 'Manipur',
  'madhya-pradesh': 'Madhya Pradesh',
  mizoram: 'Mizoram',
  nagaland: 'Nagaland',
  odisha: 'Odisha',
  punjab: 'Punjab',
  puducherry: 'Puducherry',
  rajasthan: 'Rajasthan',
  sikkim: 'Sikkim',
  telangana: 'Telangana',
  'tamil-nadu': 'Tamil Nadu',
  tripura: 'Tripura',
  'uttar-pradesh': 'Uttar Pradesh',
  uttarakhand: 'Uttarakhand',
  'west-bengal': 'West Bengal',
};

export default StatesById;
