const electedCount = [
  {
    name: 'Uttar Pradesh',
    id: 'uttar-pradesh',
    data: [64, 1, 15, 0],
    total: 80,
  },
  {
    name: 'Maharashtra',
    id: 'maharashtra',
    data: [41, 5, 0, 2],
    total: 48,
  },
  {
    name: 'West Bengal',
    id: 'west-bengal',
    data: [18, 2, 0, 22],
    total: 42,
  },
  {
    name: 'Bihar',
    id: 'bihar',
    data: [39, 1, 0, 0],
    total: 40,
  },
  {
    name: 'Tamil Nadu',
    id: 'tamil-nadu',
    data: [1, 34, 0, 4],
    total: 39,
  },
  {
    name: 'Madhya Pradesh',
    id: 'madhya-pradesh',
    data: [28, 1, 0, 0],
    total: 29,
  },
  {
    name: 'Karnataka',
    id: 'karantaka',
    data: [25, 2, 0, 1],
    total: 28,
  },
  {
    name: 'Gujarat',
    id: 'gujarat',
    data: [26, 0, 0, 0],
    total: 26,
  },
  {
    name: 'Rajasthan',
    id: 'rajasthan',
    data: [24, 0, 0, 1],
    total: 25,
  },
  {
    name: 'Andhra Pradesh',
    id: 'andhra-pradesh',
    data: [0, 0, 0, 25],
    total: 25,
  },
  {
    name: 'Odisha',
    id: 'odisha',
    data: [8, 1, 0, 12],
    total: 20,
  },
  {
    name: 'Kerala',
    id: 'kerala',
    data: [0, 19, 0, 1],
    total: 20,
  },
  {
    name: 'Telangana',
    id: 'andhra-pradesh',
    data: [4, 3, 0, 10],
    total: 17,
  },
  {
    name: 'Jharkhand',
    id: 'jharkhand',
    data: [12, 2, 0, 0],
    total: 14,
  },
  {
    name: 'Assam',
    id: 'assam',
    data: [9, 3, 0, 2],
    total: 14,
  },
  {
    name: 'Punjab',
    id: 'punjab',
    data: [4, 8, 0, 1],
    total: 13,
  },
  {
    name: 'Chhattisgarh',
    id: 'chhattisgarh',
    data: [9, 2, 0, 0],
    total: 11,
  },
  {
    name: 'Haryana',
    id: 'haryana',
    data: [10, 0, 0, 0],
    total: 10,
  },
  {
    name: 'Delhi',
    id: 'delhi',
    data: [7, 0, 0, 0],
    total: 7,
  },
  {
    name: 'Jammu and Kashmir ',
    id: 'jammu-and-kashmir',
    data: [3, 0, 0, 3],
    total: 6,
  },
  {
    name: 'Uttarakhand ',
    id: 'uttarakhhand',
    data: [5, 0, 0, 0],
    total: 5,
  },
  {
    name: 'Himachal Pradesh ',
    id: 'himachal-pradesh',
    data: [4, 0, 0, 0],
    total: 4,
  },
  {
    name: 'Meghalaya',
    id: 'meghalaya',
    data: [1, 1, 0, 0],
    total: 2,
  },
  {
    name: 'Manipur',
    id: 'manipur',
    data: [1, 0, 0, 1],
    total: 2,
  },
  {
    name: 'Anrunachal Pradesh',
    id: 'arunachal-pradesh',
    data: [2, 0, 0, 0],
    total: 2,
  },
  {
    name: 'Tripura',
    id: 'tripura',
    data: [2, 0, 0, 0],
    total: 2,
  },
  {
    name: 'Goa',
    id: 'goa',
    data: [1, 1, 0, 0],
    total: 2,
  },
  {
    name: 'Andaman & Nicobar Islands',
    id: 'andaman-and-nicobar-islands',
    data: [0, 1, 0, 0],
    total: 1,
  },
  {
    name: 'Chandigarh',
    id: 'chandigarh',
    data: [1, 0, 0, 0],
    total: 1,
  },
  {
    name: 'Dadar and Nagar Haveli',
    id: 'dadar-and-nagar-haveli',
    data: [0, 0, 0, 1],
    total: 1,
  },
  {
    name: 'Lakshadweep',
    id: 'lakshadweep',
    data: [0, 1, 0, 0],
    total: 1,
  },
  {
    name: 'Mizoram',
    id: 'mizoram',
    data: [0, 0, 0, 1],
    total: 1,
  },
  {
    name: 'Nagaland',
    id: 'nagaland',
    data: [1, 0, 0, 0],
    total: 1,
  },
  {
    name: 'Puducherry',
    id: 'puducherry',
    data: [0, 1, 0, 0],
    total: 1,
  },
  {
    name: 'Sikkim',
    id: 'sikkim',
    data: [0, 0, 0, 1],
    total: 1,
  },
  {
    name: 'Daman and Diu',
    id: 'daman-and-diu',
    data: [1, 0, 0, 0],
    total: 1,
  },
];

export default electedCount;
